### ISSUE TITLE
Screen Size

### ISSUE THREAD

**Issue by PopcornPlant** [halitsever/shotsnap#6]
Can you include an example of changing the screen size? Thanks!

**Comment by halitsever** [comment]
Hello, did you try like this:
```shotSnap.takeScreenshot({ pageUrl: 'https://google.com', saveFile: true, fileName: 'test.png', screenSize: [1920,1080] });```

if its not working like this, can you provide feedback?

**Comment by PopcornPlant** [comment]
Directly copy and pasting the code you shared above results in an image of google with size 1440x960. Thank you for your quick response btw, despite it being a few months dated. :) Very useful. 

Also, is there a way to screenshot the "mobile website" since the screensize isn't appearing to work for me.

**Comment by halitsever** [comment]
> Directly copy and pasting the code you shared above results in an image of google with size 1440x960. Thank you for your quick response btw, despite it being a few months dated. :) Very useful.
> 
> Also, is there a way to screenshot the "mobile website" since the screensize isn't appearing to work for me.

Hmm. I think i found the issue now, i'm gonna fix this issue in my free time (probably this weekend). 

Also about mobile view, yes technically its possible, you need mobile view right?

like chrome dev tool's dimension setting.

**Comment by halitsever** [comment]
**Update:**
Right now, we have 2 parameter for setting width and height:

`screenWidth`, `screenHeight`

Example:`takeScreenshot({pageUrl: "https://google.com", saveFile: true, fileName: 'test.png', screenWidth: 1920, screenHeight: 1080});`


Commit:
https://github.com/halitsever/shotsnap/commit/82de0d523960dbad250922e56d2398fb1b2134de

Thanks for using shotsnap, have nice day!
